dataset_name: ENZYMES
baseline_mode: null
N_way: 2
K_shot: 10
query_size: 10
patience: 5
dropout: 0.5
batch: 128
gin_layer: 3
gin_hid: 128
aug1: node_drop
aug2: feature_mask
t: 0.2
lr: 0.001
weight_decay: 1.0e-07
eval_interval: 100
epoch_num: 3000
use_select_sim: false
save_test_emb: true

num_token: 1
use_prompt: false
device: cuda
train_classes_num: 4
test_classes_num: 2
node_fea_size: 9
sample_input_size: 256
