# Reddit数据集配置文件
# 继承默认配置，只覆盖需要修改的参数

# 数据集配置
dataset_name: "Reddit"
baseline_mode: null

# 少样本学习参数
N_way: 3
K_shot: 5
query_size: 10
patience: 5

# 模型参数
dropout: 0.5
batch: 128

# GIN网络参数（Reddit数据集可能需要更深的网络，因为图更大更复杂）
gin_layer: 4
gin_hid: 256

# 数据增强参数
aug1: "feature_drop"
aug2: "feature_dropout"
t: 0.2

# 优化器参数
lr: 0.0005  # Reddit数据集较大，使用较小的学习率
weight_decay: 1e-6

# 训练参数
eval_interval: 100
epoch_num: 5000  # Reddit数据集需要更多训练轮数

# 其他参数
use_select_sim: false
gen_train_num: 1000  # Reddit数据集更大，生成更多训练图
gen_test_num: 50
save_test_emb: true
test_mixup: true
num_token: 1
