# 基础配置（对齐 Letter_high_ldm.yaml 风格）
dataset_name: TRIANGLES
seed: 42
baseline_mode: null
N_way: 3
K_shot: 5
query_size: 10
patience: 10
dropout: 0.5
batch: 512  # 无效参数
gin_layer: 3
gin_hid: 128
aug1: node_drop
aug2: feature_mask
t: 0.2
lr: 0.001
weight_decay: 1.0e-07
eval_interval: 100
epoch_num: 5000
use_select_sim: false
gen_train_num: 500
gen_test_num: 20
save_test_emb: true

num_token: 1
use_prompt: false
device: cuda
train_classes_num: 7
test_classes_num: 3
node_fea_size: 10
sample_input_size: 256

graph_pooling_type: sum

use_pretrained_encoder: false
encoder_ckpt_path: ./savepoint/TRIANGLES_encoder.pkl
# LDM增强配置

use_ldm_augmentation: false
use_pretrained_ldm: false # 是否跳过LDM训练并从ckpt加载
ldm_ckpt_path: ./savepoint/TRIANGLES_ldm.pkl  # 预训练LDM权重（state_dict）

# LDM相关参数  
learning_rate_ldm: 1e-4
weight_decay_ldm: 1.0e-04
num_epochs_ldm: 200000
patience_ldm: 200
time_steps: 50
beta_start: 0.0001
beta_end: 0.02 
ldm_batch_size: 512
ldm_ema_decay: 0.9              # LDM训练EMA衰减
ldm_es_interval: 100             # LDM早停检查间隔（与打印间隔一致）
condition_type: class_proto  # 训练时使用K-means，其他阶段使用真实标签聚类



#可视化处理的batch
batch_size_for_embedding: 512

# 任务评估相关
num_augmented_samples: 0
refine_support_before_training: false
refine_alpha: 0.7
refine_use_slerp: false



# wandb 配置
use_wandb: false
wandb_project: "my_fsl_project"
wandb_run_name: "TRIANGLES_experiment"
wandb_entity: "huangyrcn"  # 替换为你的团队名称
wandb_online: true

